# US Housing Market Data
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1q1PRWd1hTFQFqu2pY_e6vxMmEVh3f2AS?usp=sharing)


## Overview
| Detail Tag            | Information                                                                                        |
|-----------------------|----------------------------------------------------------------------------------------------------|
| Originally Created By | Ariel Herrera arielherrera@analyticsariel.com |
| External References   | API |
| Input Datasets        | Source name |
| Output Datasets       | Source name |
| Input Data Source     | Pandas DataFrame |
| Output Data Source    | Pandas DataFrame |

## History
| Date         | Developed By  | Reason                                                |
|--------------|---------------|-------------------------------------------------------|
| 1st Sep 2022 | Ariel Herrera | Create notebook. |

## Getting Started
1. Copy this notebook -> File -> Save a Copy in Drive
2. Directions

## Useful Resources
- [Google Colab Cheat Sheet](https://towardsdatascience.com/cheat-sheet-for-google-colab-63853778c093)

## <font color="blue">Install Packages</font>

## <font color="blue">Imports</font>

In [ ]:
from google.colab import drive, files, output # specific to Google Colab
import requests
import time

# data wrangling
import pandas as pd

# visualization
import plotly.express as px

# settings
pd.set_option('display.max_columns', None) # show all columns

## <font color="blue">Functions</font>

## <font color="blue">Locals & Constants</font>

In [ ]:
########################################################################
# OPTIONAL                                                             #
# 1) Create a file called 'api_keys.csv' to store your Rapid API key   #
# 2) Read in the file                                                  #
# 3) Set the Rapid API key to the rapid_api_key variable               #
########################################################################

# mount drive
drive.mount('/content/drive', force_remount=False)

# data location
file_dir = '/content/drive/My Drive/Colab Data/input/' # optional

Mounted at /content/drive

In [ ]:
# read in api key file
df_api_keys = pd.read_csv(file_dir + 'api_keys.csv')

# get keys
rapid_api_key = df_api_keys.loc[df_api_keys['API'] =='rapid']['KEY'].iloc[0] # replace this with your own key

## <font color="blue">Data</font>

### <font color="green">Section #1 - API Requests</font> üíª
This section will cover how to make API requests to the [US Housing Market Data API](https://bit.ly/3AHH7sY). It demonstrates how to modify your search based on different parameters.

#### <font color="purple">1. National Region</font> üèò

##### <font color="orange">Standard Query</font> ‚ú®

In [ ]:
url = "https://us-housing-market-data.p.rapidapi.com/getNational"

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers)

print(response.status_code)

200

In [ ]:
response.json()['0']

{'period_begin': '2021-05-01',
 'period_end': '2021-05-31',
 'period_duration': 30,
 'region_type': 'national',
 'region_type_id': 11,
 'table_id': 1400,
 'is_seasonally_adjusted': 'f',
 'region': ' National',
 'city': 'National',
 'state': 'U.S.',
 'state_code': 'US',
 'property_type': 'Condo/Co-op',
 'property_type_id': 3,
 'median_sale_price': 301300.0,
 'median_sale_price_mom': -0.0014343403,
 'median_sale_price_yoy': 0.1993395025,
 'median_list_price': 310943.0,
 'median_list_price_mom': 3.73406e-05,
 'median_list_price_yoy': 0.1010641588,
 'median_ppsf': 264.0,
 'median_ppsf_mom': -0.0021961071,
 'median_ppsf_yoy': 0.2544111844,
 'median_list_ppsf': 273.0,
 'median_list_ppsf_mom': -0.0025393944,
 'median_list_ppsf_yoy': 0.1303618152,
 'homes_sold': 78553.0,
 'homes_sold_mom': -0.0475370046,
 'homes_sold_yoy': 1.1197645603,
 'pending_sales': 74952.0,
 'pending_sales_mom': -0.0066427043,
 'pending_sales_yoy': 0.7191823539,
 'new_listings': 86096.0,
 'new_listings_mom': -0.053764934,
 'new_listings_yoy': 0.2516715764,
 'inventory': 128559.0,
 'inventory_mom': -0.0149912311,
 'inventory_yoy': -0.2581433282,
 'months_of_supply': 1.6365826934,
 'months_of_supply_mom': 0.0540744928,
 'months_of_supply_yoy': -3.0397518674,
 'median_dom': 25.0,
 'median_dom_mom': -4.0,
 'median_dom_yoy': -17.0,
 'avg_sale_to_list': 1.0031148577,
 'avg_sale_to_list_mom': 0.0054588257,
 'avg_sale_to_list_yoy': 0.0255306427,
 'sold_above_list': 0.3875868531,
 'sold_above_list_mom': 0.042187284,
 'sold_above_list_yoy': 0.2056949424,
 'price_drops': 0.0802048819,
 'price_drops_mom': 0.0023107702,
 'price_drops_yoy': -0.0288065879,
 'off_market_in_two_weeks': 0.4983259171,
 'off_market_in_two_weeks_mom': 0.0104932378,
 'off_market_in_two_weeks_yoy': 0.1155990166,
 'parent_metro_region': None,
 'parent_metro_region_metro_code': None,
 'last_updated': '2022-08-14 14:47:34'}

In [ ]:
df_national = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_national)))
print('Num of columns: {}'.format(len(df_national.columns)))
year_list = df_national.apply(lambda x: x['period_begin'].split('-')[0], axis=1).unique().tolist()
year_list.sort()
print('Years: {}'.format( year_list ))
df_national

Num of rows: 1397
Num of columns: 58
Years: ['2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2021-05-01,2021-05-31,30,national,11,1400,f,National,National,U.S.,US,Condo/Co-op,3,301300.000000,-0.001434,0.199340,310943.000000,0.000037,0.101064,264.000000,-0.002196,0.254411,273.000000,-0.002539,0.130362,78553.000000,-0.047537,1.119765,74952.000000,-0.006643,0.719182,86096.000000,-0.053765,0.251672,128559.000000,-0.014991,-0.258143,1.636583,0.054074,-3.039752,25.000000,-4.0,-17.0,1.003115,0.005459,0.025531,0.387587,0.042187,0.205695,0.080205,0.002311,-0.028807,0.498326,0.010493,0.115599,None,None,2022-08-14 14:47:34
1,2012-07-01,2012-07-31,30,national,11,1400,f,National,National,U.S.,US,Condo/Co-op,3,156724.000000,-0.037308,0.056702,160842.000000,-0.015689,0.019390,133.000000,-0.020710,0.045851,135.000000,-0.023692,0.007986,52275.000000,-0.085909,0.185500,36131.000000,-0.029908,0.282090,61937.000000,-0.048443,0.052594,247999.000000,-0.023823,-0.217345,4.744101,0.301729,-2.441865,73.000000,-2.0,-28.0,0.965701,0.001409,0.011662,0.185658,0.005620,0.038733,0.061762,-0.000419,-0.019492,0.284747,-0.001828,0.067277,None,None,2022-08-14 14:47:34
2,2016-12-01,2016-12-31,30,national,11,1400,f,National,National,U.S.,US,Condo/Co-op,3,224061.000000,-0.042726,0.083361,226118.000000,-0.044127,0.102278,189.000000,-0.043132,0.075694,190.000000,-0.031668,0.098283,54289.000000,0.011810,-0.009573,35360.000000,-0.155042,0.058108,38786.000000,-0.249387,-0.030921,153453.000000,-0.109655,-0.120609,2.826609,-0.385620,-0.356899,51.000000,4.0,-4.0,0.974272,-0.002575,0.002278,0.175381,-0.012982,0.005919,0.066626,-0.064348,-0.010251,0.282451,-0.034445,0.027202,None,None,2022-08-14 14:47:34
3,2013-07-01,2013-07-31,30,national,11,1400,f,National,National,U.S.,US,Multi-Family (2-4 Unit),4,202779.000000,0.032906,0.166361,210828.000000,-0.004812,0.188509,93.000000,-0.007394,0.127512,99.000000,0.002507,0.191431,10108.000000,0.089694,0.236315,7724.000000,0.060080,0.233784,15379.000000,0.057862,0.170383,54662.000000,0.033824,-0.060691,5.407789,-0.292248,-1.709922,58.000000,2.0,-7.0,0.965301,-0.002252,0.010951,0.267404,-0.014442,0.025173,0.056769,0.007539,-0.002524,0.291058,-0.019936,0.020028,None,None,2022-08-14 14:47:34
4,2020-06-01,2020-06-30,30,national,11,1400,f,National,National,U.S.,US,Townhouse,13,281519.000000,0.035578,0.052216,292494.000000,0.006157,0.078289,173.000000,0.045014,0.067908,181.000000,0.003020,0.077475,55586.000000,0.372505,-0.038853,58874.000000,0.236137,0.143161,72518.000000,0.169892,0.070919,116692.000000,-0.025694,-0.152704,2.099297,-0.857984,-0.282083,37.000000,1.0,4.0,0.990351,0.001053,0.000262,0.272010,0.006439,-0.003565,0.108728,0.005704,-0.026907,0.473103,0.052687,0.061865,None,None,2022-08-14 14:47:34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1392,2019-08-01,2019-08-31,30,national,11,1400,t,National,National,U.S.,US,Condo/Co-op,3,253450.248868,0.018906,0.045311,270828.070374,0.019373,0.053014,214.430900,0.008084,0.045841,229.591479,0.004277,0.034774,57174.359079,-0.017971,-0.058143,47530.227144,-0.047627,-0.088834,67836.065441,0.026783,-0.076370,174206.684528,-0.010807,0.038785,2.925128,-0.080073,0.193883,44.281049,-1.0,8.0,0.978998,0.000770,-0.002553,0.187666,0.000311,-0.027597,0.117818,-0.004730,0.000957,0.352348,0.002460,-0.039103,None,None,2022-08-16 00:00:00
1393,2021-02-01,2021-02-28,30,national,11,1400,t,National,National,U.S.,US,Condo/Co-op,3,284134.174945,-0.000375,0.066501,304733.159383,0.015196,0.110109,246.020467,-0.003430,0.081607,266.433041,0.005892,0.109650,69508.532375,0.000289,0.170706,62803.443829,-0.020043,0.234736,73178.348386,-0.054147,0.034213,146368.560149,-0.069442,-0.136701,2.150299,-0.214999,-0.621574,36.377618,1.0,-7.0,0.988687,-0.000348,0.007197,0.254822,0.008093,0.065834,0.103493,-0.004516,-0.015799,0.396412,0.009126,0.040792,None,None,2022-08-16 00:00:00
1394,2021-01-01,2021-01-31,30,national,11,1400,t,National,National,U.S.,US,All Residential,-1,343587.556996,0.014564,0.145960,348961.153595,-0.011566,0.118758,185.333206,0.016125,0.149425,190.365028,-0.006147,0.141972,623646.030741,0.006434,0.208519,617662.258566,0.021825,0.318332,674696.563044,-0.045574,0.027978,971299.859486,-0.054547,-0.338820,1.557877,-0.053337,-1.427719,24.157580,-2.0,-22.0,1.001687,0.001989,0.016664,0.397412,0.011353,0.170390,0.092742,-0.002480,-0.038222,0.492143,-0.018089,0.098657,None,None,2022-08-16 00:00:00
1395,2013-06-01,2013-06-30,30,national,11,1400,t,National,National,U.S.,US,Townhouse,13,194640.353543,0.035905,0.154180,197874.256178,0.027022,0.145400,123.072594,0.024408,0.120744,125.041475,0.008231,0.107834,36549.453915,0.016315,0.185653,29643.594325,0.037021,0.333317,45067.426805,-0.005062,0.188056,133407.604587,-0.012610,-0.095307,3.740719,-0.036043,-1.207920,52.424188,-2.0,-25.0,0.981341,0.001053,0.011067,0.243214,0.000113,0.055357,0.056283,-0.001440,-0.005885,0.380256,0.005887,0.055374,None,None,2022-08-16 00:00:00
1396,2020-07-01,2020-07-31,30,national,11,1400,t,National,National,U.S.,US,Townhouse,13,281656.727208,0.021590,0.070500,297109.304850,0.030687,0.108068,173.445311,0.014719,0.077771,183.885504,0.026525,0.110442,58892.395356,0.293333,0.179985,56028.058286,0.064558,0.224885,66297.409965,0.094938,0.145043,103062.587771,-0.059792,-0.187444,1.671156,-0.667865,-0.766238,38.431639,-7.0,-1.0,0.989278,0.003662,0.003517,0.278805,0.038770,0.034105,0.092318,-0.008508,-0.032081,0.474949,0.016514,0.088210,None,None,2022-08-16 00:00:00

##### <font color="orange">Enriched Query</font> üåü

In [ ]:
url = "https://us-housing-market-data.p.rapidapi.com/getNationalEnriched"

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers)
df_national_e = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_national_e)))
print('Num of columns: {}'.format(len(df_national_e.columns)))
df_national_e.tail()

Num of rows: 254
Num of columns: 69

,fred.date,fred.total_population,fred.inflation_rate,fred.consumer_price_index,fred.interest_rate,fred.household_debt_to_gdp,fred.working_age_population,fred.total_unfilled_job_vacancies,fred.employment_rate,fred.unemployment_rate,fred.long_term_gov_bond_yield_10_yr_rate,redfin.period_begin,redfin.period_end,redfin.period_duration,redfin.region_type,redfin.region_type_id,redfin.table_id,redfin.is_seasonally_adjusted,redfin.region,redfin.city,redfin.state,redfin.state_code,redfin.property_type,redfin.property_type_id,redfin.median_sale_price,redfin.median_sale_price_mom,redfin.median_sale_price_yoy,redfin.median_list_price,redfin.median_list_price_mom,redfin.median_list_price_yoy,redfin.median_ppsf,redfin.median_ppsf_mom,redfin.median_ppsf_yoy,redfin.median_list_ppsf,redfin.median_list_ppsf_mom,redfin.median_list_ppsf_yoy,redfin.homes_sold,redfin.homes_sold_mom,redfin.homes_sold_yoy,redfin.pending_sales,redfin.pending_sales_mom,redfin.pending_sales_yoy,redfin.new_listings,redfin.new_listings_mom,redfin.new_listings_yoy,redfin.inventory,redfin.inventory_mom,redfin.inventory_yoy,redfin.months_of_supply,redfin.months_of_supply_mom,redfin.months_of_supply_yoy,redfin.median_dom,redfin.median_dom_mom,redfin.median_dom_yoy,redfin.avg_sale_to_list,redfin.avg_sale_to_list_mom,redfin.avg_sale_to_list_yoy,redfin.sold_above_list,redfin.sold_above_list_mom,redfin.sold_above_list_yoy,redfin.price_drops,redfin.price_drops_mom,redfin.price_drops_yoy,redfin.off_market_in_two_weeks,redfin.off_market_in_two_weeks_mom,redfin.off_market_in_two_weeks_yoy,redfin.parent_metro_region,redfin.parent_metro_region_metro_code,redfin.last_updated
249,2022-05-01,331893745.0,4.697859,1.102352,0.25,80.004218,207356962.3,11303000.0,71.376155,3.619301,2.90,2022-05-01,2022-05-31,30,national,11,1400,f,National,National,U.S.,US,All Residential,-1,430279.000000,0.014482,0.148871,436230.000000,0.004076,0.150667,237.000000,0.003048,0.167976,234.000000,0.000036,0.148037,598037.000000,0.068691,-0.059576,605036.000000,0.064770,-0.092131,762052.000000,0.061112,0.014448,8.945260e+05,0.138379,0.104516,1.495771,0.091566,0.222218,17.000000,-1.0,1.0,1.030975,-0.000418,0.009278,0.591556,0.004003,0.057327,0.112783,0.034045,0.041955,0.553293,-0.031837,-0.056050,None,None,2022-08-14 14:47:34
250,2022-06-01,331893745.0,4.697859,1.373608,0.25,80.004218,207486228.4,10698000.0,71.242452,3.619301,3.14,2022-06-01,2022-06-30,30,national,11,1400,t,National,National,U.S.,US,All Residential,-1,409175.683445,-0.005756,0.105047,421259.882509,0.005073,0.132965,225.571619,-0.007112,0.119057,230.105752,0.001663,0.132670,522431.766752,-0.037245,-0.142791,495044.424217,-0.021025,-0.137105,628858.555607,0.001885,-0.014528,9.573217e+05,0.131645,0.229824,1.766516,0.120939,0.484744,24.073589,1.0,3.0,1.014005,-0.006656,-0.003256,0.487826,-0.030244,-0.008061,0.130727,0.008413,0.047069,0.444172,-0.036037,-0.108216,None,None,2022-08-16 00:00:00
251,2022-06-01,331893745.0,4.697859,1.373608,0.25,80.004218,207486228.4,10698000.0,71.242452,3.619301,3.14,2022-06-01,2022-06-30,30,national,11,1400,f,National,National,U.S.,US,All Residential,-1,427032.000000,-0.007548,0.107599,431146.000000,-0.011654,0.134120,233.000000,-0.015285,0.128376,231.000000,-0.012235,0.131910,620753.000000,0.037985,-0.155054,579661.000000,-0.041939,-0.153437,803415.000000,0.054278,-0.018117,1.067635e+06,0.193520,0.208695,1.719902,0.224131,0.517594,18.000000,1.0,3.0,1.022614,-0.008362,-0.002714,0.553703,-0.037852,-0.009614,0.168510,0.055727,0.077979,0.460568,-0.092725,-0.112371,None,None,2022-08-14 14:47:34
252,2022-07-01,331893745.0,4.697859,1.373608,0.25,80.004218,207494240.0,10698000.0,71.301078,3.619301,2.90,2022-07-01,2022-07-31,30,national,11,1400,f,National,National,U.S.,US,All Residential,-1,412739.000000,-0.033470,0.076507,421684.000000,-0.021947,0.121120,227.000000,-0.027410,0.097113,229.000000,-0.007013,0.122274,526945.000000,-0.151120,-0.232854,547322.000000,-0.055789,-0.154453,670766.000000,-0.165107,-0.166867,1.132745e+06,0.060986,0.152806,2.149647,0.429744,0.719143,21.000000,3.0,6.0,1.010228,-0.012385,-0.012427,0.473373,-0.080330,-0.082164,0.209252,0.040741,0.096869,0.387740,-0.072827,-0.137117,None,None,2022-08-14 14:47:34
253,2022-07-01,331893745.0,4.697859,1.373608,0.25,80.004218,207494240.0,10698000.0,71.301078,3.619301,2.90,2022-07-01,2022-07-31,30,national,11,1400,t,National,National,U.S.,US,All Residential,-1,407581.194422,-0.003897,0.081770,422270.872787,0.002400,0.122709,224.594095,-0.004334,0.097307,230.801784,0.003025,0.124880,501114.548252,-0.040804,-0.193340,492698.200222,-0.004739,-0.132912,626852.368034,-0.003190,-0.134652,9.885315e+05,0.032601,0.183467,1.858384,0.091868,0.528500,26.124405,2.0,6.0,1.006263,-0.007742,-0.011951,0.428298,-0.059528,-0.072843,0.137691,0.006965,0.051550,0.411303,-0.032869,-0.140901,None,None,2022-08-16 00:00:00

#### <font color="purple">2. Metro Region</font> üèò

##### <font color="orange">Search Valid Metro Ids</font> üîç

In [ ]:
url = "https://us-housing-market-data.p.rapidapi.com/getRegionId"

querystring = {"region_type":"metro"}

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)
df_metro_ids = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_metro_ids)))
df_metro_ids.head()

Num of rows: 795

  region_id                       region   type
1     15680    California, MD metro area  metro
2     16300  Cedar Rapids, IA metro area  metro
3     44140   Springfield, MA metro area  metro
4     40420      Rockford, IL metro area  metro
5     19340     Davenport, IA metro area  metro

In [ ]:
metro_id_search_str = 'Tampa'
df_metro_id_filter = df_metro_ids.loc[df_metro_ids['region'].str.contains(metro_id_search_str)]
metro_region_id = df_metro_id_filter['region_id'].iloc[0]
print('Region ID for {0} is {1}'.format(metro_id_search_str, metro_region_id))

Region ID for Tampa is 45300

##### <font color="orange">Standard Query</font> ‚ú®

In [ ]:
url = "https://us-housing-market-data.p.rapidapi.com/getMetro"

querystring = {"metro_id":metro_region_id}

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)
df_metro = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_metro)))
print('Num of columns: {}'.format(len(df_metro.columns)))
print('Last updated: {}'.format(df_metro['last_updated'].unique().tolist()[0]))
print('Lastest period: {}'.format(df_metro['period_end'].max()))
df_metro.head()

Num of rows: 1143
Num of columns: 58
Last updated: 2022-08-14 14:44:22
Lastest period: 2022-07-31

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2012-07-01,2012-07-31,30,metro,-2,45300,f,"Tampa, FL metro area",None,None,FL,All Residential,-1,120000.0,-0.016756,0.071429,129900.0,0.000000,0.083403,75.024201,-0.017117,0.055028,81.194172,0.000903,0.061337,3969.0,-0.075041,0.113949,1914.0,-0.087268,0.324567,5004.0,0.086645,0.211622,23340.0,0.007859,-0.064454,5.9,0.5,-1.1,111.0,0.0,-20.0,0.955037,0.000087,0.015108,0.165281,0.010538,0.021020,NaN,NaN,NaN,0.091954,0.008978,0.013753,"Tampa, FL",45300,2022-08-14 14:44:22
1,2022-04-01,2022-04-30,30,metro,-2,45300,f,"Tampa, FL metro area",None,None,FL,Single Family Residential,6,400000.0,0.038961,0.290323,415000.0,0.040100,0.261398,230.985915,0.045757,0.318652,239.822652,0.041961,0.302498,4520.0,-0.090543,-0.114940,4480.0,-0.065693,-0.088134,5416.0,0.018620,-0.010053,3923.0,0.241456,0.034001,0.9,0.3,0.2,7.0,0.0,-3.0,1.019629,0.004638,0.019975,0.546903,0.046299,0.159200,0.251338,0.017161,0.041006,0.757589,-0.007166,0.046618,"Tampa, FL",45300,2022-08-14 14:44:22
2,2020-09-01,2020-09-30,30,metro,-2,45300,f,"Tampa, FL metro area",None,None,FL,Multi-Family (2-4 Unit),4,235000.0,-0.160714,0.270270,279900.0,-0.031488,0.332857,132.874016,-0.019239,0.195443,166.606061,0.029037,0.289631,67.0,0.175439,0.155172,53.0,0.039216,0.232558,75.0,-0.050633,0.470588,143.0,0.091603,-0.077419,2.1,-0.2,-0.6,42.0,13.0,-2.0,0.946287,-0.015999,0.021042,0.164179,-0.028803,0.043489,0.146853,-0.028719,-0.085405,0.547170,0.037366,0.128565,"Tampa, FL",45300,2022-08-14 14:44:22
3,2018-02-01,2018-02-28,30,metro,-2,45300,f,"Tampa, FL metro area",None,None,FL,Multi-Family (2-4 Unit),4,200000.0,0.052632,0.324503,209950.0,-0.045682,0.235727,97.520661,-0.053283,0.086593,115.770674,-0.007445,0.189256,49.0,0.289474,0.065217,50.0,-0.107143,0.282051,77.0,-0.144444,0.013158,193.0,0.048913,0.206250,3.9,-0.9,0.4,25.0,0.0,0.0,0.934621,-0.014865,-0.014263,0.142857,0.090226,-0.052795,0.207254,-0.048181,0.013504,0.460000,-0.147143,-0.232308,"Tampa, FL",45300,2022-08-14 14:44:22
4,2014-06-01,2014-06-30,30,metro,-2,45300,f,"Tampa, FL metro area",None,None,FL,Townhouse,13,137750.0,-0.015368,0.007313,150175.0,0.042882,0.080784,91.625295,0.031278,0.094421,95.485411,0.003433,0.091602,328.0,0.015480,-0.012048,245.0,-0.209677,0.276042,396.0,0.076087,0.058824,1094.0,-0.044541,-0.215208,3.3,-0.2,-0.9,55.0,-21.0,-37.0,0.970033,-0.000276,-0.004180,0.097561,-0.091294,-0.122319,0.191042,-0.240399,NaN,0.236735,-0.011652,0.116943,"Tampa, FL",45300,2022-08-14 14:44:22

#### <font color="purple">3. State Region</font> üèò
Locate valid state abbreviation codes by visiting the BLS website - [USPS State Abbreviations and FIPS Codes](https://www.bls.gov/respondents/mwr/electronic-data-interchange/appendix-d-usps-state-abbreviations-and-fips-codes.htm)

##### <font color="orange">Standard Query</font> ‚ú®

In [ ]:
state_code = "FL" # enter state code abbreviations
url = "https://us-housing-market-data.p.rapidapi.com/getState"

querystring = {"state_code": state_code} 

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)
df_state = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_state)))
print('Num of columns: {}'.format(len(df_state.columns)))
print('Last updated: {}'.format(df_state['last_updated'].unique().tolist()[0]))
print('Lastest period: {}'.format(df_state['period_end'].max()))
df_state.head()

Num of rows: 635
Num of columns: 58
Last updated: 2022-08-14 14:44:22
Lastest period: 2022-07-31

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2017-09-01,2017-09-30,30,state,4,19,f,Florida,None,Florida,FL,Condo/Co-op,3,165100,-0.016695,0.096782,267700.0,-0.011764,0.023962,154.0,-0.005228,0.082397,170.0,-0.006014,0.035499,5349,-0.245131,-0.175936,2936.0,-0.389351,-0.250638,5667.0,-0.367099,-0.344325,35097.0,-0.025354,-0.077269,6.6,1.5,0.7,78.0,-2.0,-9.0,0.951943,0.000652,0.000739,0.056833,0.001513,-0.017115,0.095592,-0.051950,-0.050296,0.214622,-0.071319,-0.052755,South Region,None,2022-08-14 14:44:22
1,2022-02-01,2022-02-28,30,state,4,19,f,Florida,None,Florida,FL,Condo/Co-op,3,290200,0.017399,0.270803,434900.0,0.039059,0.239578,264.0,0.037503,0.358375,284.0,0.035903,0.271819,8302,0.072610,-0.050114,8487.0,0.056912,0.114511,10443.0,0.018929,-0.008639,16520.0,-0.018244,-0.432497,2.0,-0.2,-1.3,38.0,-3.0,-29.0,0.987634,0.005339,0.026675,0.274392,0.043255,0.197962,0.092857,-0.011321,-0.051458,0.501488,0.048376,0.138479,South Region,None,2022-08-14 14:44:22
2,2012-05-01,2012-05-31,30,state,4,19,f,Florida,None,Florida,FL,Multi-Family (2-4 Unit),4,103400,-0.081055,0.186150,146600.0,-0.042796,0.085994,47.0,-0.068863,0.016161,93.0,-0.044466,0.062069,260,-0.061372,-0.029851,119.0,-0.040323,0.133333,215.0,0.053922,0.279762,1081.0,-0.005520,-0.158100,4.2,0.3,-0.6,94.0,-9.0,-1.0,0.926874,-0.012114,0.006543,0.188462,-0.017315,-0.005568,NaN,NaN,NaN,0.107834,-0.131951,0.003730,South Region,None,2022-08-14 14:44:22
3,2016-12-01,2016-12-31,30,state,4,19,f,Florida,None,Florida,FL,All Residential,-1,220100,0.033389,0.097260,241500.0,-0.016191,0.073513,138.0,0.015847,0.086929,150.0,-0.005893,0.067962,31155,0.121773,-0.024394,18880.0,-0.101637,0.014563,30444.0,-0.163810,-0.005456,131465.0,-0.030887,-0.013544,4.2,-0.7,0.0,65.0,-2.0,-4.0,0.964886,-0.000746,-0.000091,0.118633,-0.007677,-0.022064,0.154726,-0.025953,0.006455,0.275378,-0.012300,0.042381,South Region,None,2022-08-14 14:44:22
4,2015-04-01,2015-04-30,30,state,4,19,f,Florida,None,Florida,FL,Townhouse,13,165800,0.025619,0.094292,224200.0,0.009109,0.127729,112.0,0.006506,0.080177,137.0,-0.000640,0.129007,2523,-0.021334,0.172943,2092.0,0.078907,-0.032825,3117.0,-0.041218,0.264503,9628.0,-0.019951,0.215196,3.8,0.0,0.1,71.0,4.0,-7.0,0.963949,0.001975,-0.002744,0.122870,0.004561,-0.037056,0.163274,-0.020053,-0.002446,0.256197,-0.007494,0.061328,South Region,None,2022-08-14 14:44:22

##### <font color="orange">Enriched Query</font> üåü

In [ ]:
url = "https://us-housing-market-data.p.rapidapi.com/getStateEnriched"

querystring = {"state_code":state_code}

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)
df_state_e = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_state_e)))
print('Num of columns: {}'.format(len(df_state_e.columns)))
df_state_e.tail()

Num of rows: 127
Num of columns: 70

,fred.date,fred.total_population,fred.median_household_income,fred.median_list_price,fred.median_inventory,fred.median_days_on_market,fred.rental_vacancy_rate,fred.home_ownership_rate,fred.home_value_index,fred.unemployment_rate,fred.building_permits_housing_units,fred.gdp,redfin.period_begin,redfin.period_end,redfin.period_duration,redfin.region_type,redfin.region_type_id,redfin.table_id,redfin.is_seasonally_adjusted,redfin.region,redfin.city,redfin.state,redfin.state_code,redfin.property_type,redfin.property_type_id,redfin.median_sale_price,redfin.median_sale_price_mom,redfin.median_sale_price_yoy,redfin.median_list_price,redfin.median_list_price_mom,redfin.median_list_price_yoy,redfin.median_ppsf,redfin.median_ppsf_mom,redfin.median_ppsf_yoy,redfin.median_list_ppsf,redfin.median_list_ppsf_mom,redfin.median_list_ppsf_yoy,redfin.homes_sold,redfin.homes_sold_mom,redfin.homes_sold_yoy,redfin.pending_sales,redfin.pending_sales_mom,redfin.pending_sales_yoy,redfin.new_listings,redfin.new_listings_mom,redfin.new_listings_yoy,redfin.inventory,redfin.inventory_mom,redfin.inventory_yoy,redfin.months_of_supply,redfin.months_of_supply_mom,redfin.months_of_supply_yoy,redfin.median_dom,redfin.median_dom_mom,redfin.median_dom_yoy,redfin.avg_sale_to_list,redfin.avg_sale_to_list_mom,redfin.avg_sale_to_list_yoy,redfin.sold_above_list,redfin.sold_above_list_mom,redfin.sold_above_list_yoy,redfin.price_drops,redfin.price_drops_mom,redfin.price_drops_yoy,redfin.off_market_in_two_weeks,redfin.off_market_in_two_weeks_mom,redfin.off_market_in_two_weeks_yoy,redfin.parent_metro_region,redfin.parent_metro_region_metro_code,redfin.last_updated
122,2022-03-01,21781128.0,57435.0,449950.0,36544.0,37.0,6.5,67.2,366088,3.2,13267.0,1226297.5,2022-03-01,2022-03-31,30,state,4,19,f,Florida,None,Florida,FL,All Residential,-1,388500,0.040755,0.227207,421300.0,0.040109,0.246048,245.0,0.041102,0.278124,261.0,0.025556,0.273816,45866,0.304457,-0.108342,42547.0,0.184164,-0.069136,50564.0,0.183947,0.001684,57300.0,0.024239,-0.206635,1.2,-0.4,-0.2,24.0,-4.0,-15.0,1.001569,0.006494,0.020949,0.407208,0.055881,0.191613,0.145183,0.032356,0.004067,0.552688,-0.000608,0.071801,South Region,None,2022-08-14 14:44:22
123,2022-04-01,21781128.0,57435.0,472990.0,39429.0,35.0,6.5,67.2,376793,3.0,13511.0,1226297.5,2022-04-01,2022-04-30,30,state,4,19,f,Florida,None,Florida,FL,All Residential,-1,400000,0.029864,0.226987,434500.0,0.031373,0.256163,251.0,0.030187,0.275046,267.0,0.025489,0.276946,42746,-0.068126,-0.164366,39861.0,-0.063218,-0.057637,49186.0,-0.027445,-0.020336,61836.0,0.078880,-0.131212,1.4,0.2,0.0,22.0,-2.0,-10.0,1.005024,0.003457,0.018989,0.438684,0.031499,0.171374,0.162155,0.016957,0.036844,0.536246,-0.016431,0.031280,South Region,None,2022-08-14 14:44:22
124,2022-05-01,21781128.0,57435.0,490768.0,49266.0,32.0,6.5,67.2,387543,2.9,12635.0,1226297.5,2022-05-01,2022-05-31,30,state,4,19,f,Florida,None,Florida,FL,All Residential,-1,410100,0.025220,0.235568,437900.0,0.007925,0.246245,257.0,0.019121,0.278774,267.0,0.001300,0.252400,42895,0.003486,-0.086174,39409.0,-0.011339,-0.052805,52213.0,0.061542,0.071146,70165.0,0.134695,-0.004582,1.6,0.2,0.1,22.0,0.0,-8.0,1.004126,-0.000897,0.013423,0.433407,-0.005277,0.118196,0.220979,0.058824,0.095227,0.504711,-0.031535,-0.003551,South Region,None,2022-08-14 14:44:22
125,2022-06-01,21781128.0,57435.0,498500.0,60479.0,34.0,6.5,67.2,396607,2.8,12002.0,1226297.5,2022-06-01,2022-06-30,30,state,4,19,f,Florida,None,Florida,FL,All Residential,-1,410500,0.000970,0.203545,437800.0,-0.000265,0.245859,255.0,-0.007644,0.234818,266.0,-0.007345,0.237070,41279,-0.037673,-0.189065,36429.0,-0.075617,-0.138672,53916.0,0.032616,0.082281,82737.0,0.179178,0.173391,2.0,0.4,0.6,23.0,1.0,-5.0,0.998515,-0.005611,0.003686,0.390223,-0.043185,0.036530,0.296615,0.075635,0.148652,0.442105,-0.062606,-0.051901,South Region,None,2022-08-14 14:44:22
126,2022-07-01,21781128.0,57435.0,485000.0,76833.0,36.0,6.5,67.2,402837,2.7,9985.0,1226297.5,2022-07-01,2022-07-31,30,state,4,19,f,Florida,None,Florida,FL,All Residential,-1,400000,-0.025556,0.172013,429800.0,-0.018276,0.210917,250.0,-0.024454,0.197842,263.0,-0.010884,0.217574,33100,-0.198081,-0.265717,34197.0,-0.061193,-0.128850,46427.0,-0.138837,-0.055363,89877.0,0.086416,0.214160,2.7,0.7,1.1,24.0,1.0,-3.0,0.990480,-0.008035,-0.004726,0.321178,-0.069073,-0.044366,0.345138,0.048504,0.178152,0.365835,-0.076278,-0.104908,South Region,None,2022-08-14 14:44:22

#### <font color="purple">4. County Region</font> üèò

##### <font color="orange">Search Valid County Ids</font> üîç

In [ ]:
url = "https://us-housing-market-data.p.rapidapi.com/getRegionId"

querystring = {"region_type":"county"}

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)
df_county_ids = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_county_ids)))
df_county_ids.head()

Num of rows: 2375

    region_id                region    type
844      2170  Champaign County, OH  county
845       490     Putnam County, FL  county
846      1668     Monroe County, MO  county
847       741   Gallatin County, IL  county
848      2919    Wasatch County, UT  county

In [ ]:
county_id_search_str = 'Hillsborough'
df_county_id_filter = df_county_ids.loc[df_county_ids['region'].str.contains(county_id_search_str)]
county_region_id = df_county_id_filter['region_id'].iloc[0]
print('Region ID for {0} is {1}'.format(county_id_search_str, county_region_id))

Region ID for Hillsborough is 464

##### <font color="orange">Standard Query</font> ‚ú®

In [ ]:
url = "https://us-housing-market-data.p.rapidapi.com/getCounty"

querystring = {"county_id":county_region_id}

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)
df_county = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_county)))
print('Num of columns: {}'.format(len(df_county.columns)))
print('Last updated: {}'.format(df_county['last_updated'].unique().tolist()[0]))
print('Lastest period: {}'.format(df_county['period_end'].max()))
df_county.head()

Num of rows: 635
Num of columns: 58
Last updated: 2022-08-14 14:44:22
Lastest period: 2022-07-31

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2017-07-01,2017-07-31,30,county,5,464,f,"Hillsborough County, FL",None,Florida,FL,Multi-Family (2-4 Unit),4,120250.0,0.052516,-0.075000,229000.0,-0.000415,0.065116,73.125397,0.085819,0.074029,124.739040,-0.004349,0.060875,16.0,-0.111111,0.066667,16.0,0.142857,0.333333,21.0,0.615385,-0.086957,43.0,-0.044444,-0.022727,2.7,0.2,-0.2,23.0,-14.0,-24.0,0.932443,0.003325,0.040149,0.125000,0.013889,0.125000,0.325581,-0.007752,0.121036,0.625000,-0.017857,0.375000,"Tampa, FL",45300.0,2022-08-14 14:44:22
1,2017-05-01,2017-05-31,30,county,5,464,f,"Hillsborough County, FL",None,Florida,FL,Townhouse,13,157990.0,-0.042485,0.074762,235000.0,0.026201,0.048896,103.225594,-0.020425,0.063748,126.103833,0.009816,0.072670,275.0,0.238739,0.145833,256.0,0.080169,0.312821,312.0,0.164179,0.339056,479.0,0.016985,-0.125912,1.7,-0.4,-0.6,20.0,-5.0,-29.0,0.981810,0.001660,0.003552,0.185455,0.041310,0.047955,0.237996,0.008696,0.062813,0.429688,-0.106177,0.050200,"Tampa, FL",45300.0,2022-08-14 14:44:22
2,2012-02-01,2012-02-29,30,county,5,464,f,"Hillsborough County, FL",None,Florida,FL,Townhouse,13,100902.5,0.219439,0.261281,129900.0,-0.000769,0.115500,68.774283,0.220373,0.227811,76.123128,-0.015669,0.078984,134.0,0.264151,0.145299,48.0,-0.020408,0.043478,153.0,-0.072727,-0.120690,835.0,-0.001196,-0.262367,6.2,-1.7,-3.5,117.0,-27.0,-3.0,0.971567,0.009990,0.022018,0.164179,0.013236,0.061615,NaN,NaN,NaN,0.083333,-0.018707,-0.003623,"Tampa, FL",45300.0,2022-08-14 14:44:22
3,2022-01-01,2022-01-31,30,county,5,464,f,"Hillsborough County, FL",None,Florida,FL,Single Family Residential,6,375000.0,0.013514,0.279392,369900.0,0.046963,0.297895,204.910070,0.021005,0.280889,208.117685,0.034216,0.283275,1437.0,-0.291071,-0.012371,1602.0,0.079515,-0.067520,1629.0,0.153683,-0.088416,1186.0,-0.122781,-0.344027,0.8,0.1,-0.4,12.0,2.0,-3.0,0.999790,-0.003901,0.009381,0.412665,-0.003714,0.152184,0.197302,-0.026071,-0.065972,0.662297,0.029548,0.054032,"Tampa, FL",45300.0,2022-08-14 14:44:22
4,2021-04-01,2021-04-30,30,county,5,464,f,"Hillsborough County, FL",None,Florida,FL,Multi-Family (2-4 Unit),4,220500.0,-0.081250,0.142487,320000.0,0.032258,0.187869,148.533951,0.090414,0.201982,176.259795,0.036552,0.200532,24.0,-0.111111,1.181818,18.0,-0.250000,1.250000,31.0,0.631579,1.214286,41.0,0.205882,-0.127660,1.7,0.4,-2.6,7.0,-8.0,-15.0,0.981678,0.016020,0.017840,0.291667,0.069444,0.018939,0.121951,-0.113343,-0.154645,0.666667,0.291667,0.041667,"Tampa, FL",45300.0,2022-08-14 14:44:22

##### <font color="orange">Enriched Query</font> üåü

In [ ]:
url = "https://us-housing-market-data.p.rapidapi.com/getCountyEnriched"

querystring = {"county_id":county_region_id}

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)
df_county_e = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_county_e)))
print('Num of columns: {}'.format(len(df_county_e.columns)))
df_county_e.tail()

Num of rows: 127
Num of columns: 74

,fred.date,fred.total_population,fred.median_household_income,fred.median_list_price,fred.median_inventory,fred.median_days_on_market,fred.market_hotness_rank,fred.count_of_crime_offenses,fred.poverty_rate,fred.unemployment_rate,fred.civilian_labor_force,fred.building_permits_housing_units,fred.home_ownership_rate,fred.gdp,fred.county,fred.state,redfin.period_begin,redfin.period_end,redfin.period_duration,redfin.region_type,redfin.region_type_id,redfin.table_id,redfin.is_seasonally_adjusted,redfin.region,redfin.city,redfin.state,redfin.state_code,redfin.property_type,redfin.property_type_id,redfin.median_sale_price,redfin.median_sale_price_mom,redfin.median_sale_price_yoy,redfin.median_list_price,redfin.median_list_price_mom,redfin.median_list_price_yoy,redfin.median_ppsf,redfin.median_ppsf_mom,redfin.median_ppsf_yoy,redfin.median_list_ppsf,redfin.median_list_ppsf_mom,redfin.median_list_ppsf_yoy,redfin.homes_sold,redfin.homes_sold_mom,redfin.homes_sold_yoy,redfin.pending_sales,redfin.pending_sales_mom,redfin.pending_sales_yoy,redfin.new_listings,redfin.new_listings_mom,redfin.new_listings_yoy,redfin.inventory,redfin.inventory_mom,redfin.inventory_yoy,redfin.months_of_supply,redfin.months_of_supply_mom,redfin.months_of_supply_yoy,redfin.median_dom,redfin.median_dom_mom,redfin.median_dom_yoy,redfin.avg_sale_to_list,redfin.avg_sale_to_list_mom,redfin.avg_sale_to_list_yoy,redfin.sold_above_list,redfin.sold_above_list_mom,redfin.sold_above_list_yoy,redfin.price_drops,redfin.price_drops_mom,redfin.price_drops_yoy,redfin.off_market_in_two_weeks,redfin.off_market_in_two_weeks_mom,redfin.off_market_in_two_weeks_yoy,redfin.parent_metro_region,redfin.parent_metro_region_metro_code,redfin.last_updated
122,2022-03-01,1478194.0,65272.0,426900.0,4799.0,31.0,225.0,10606.0,14.0,2.5,789073,11281.0,61.423444,96832749.0,Hillsborough County,FL,2022-03-01,2022-03-31,30,county,5,464,f,"Hillsborough County, FL",None,Florida,FL,All Residential,-1,377990.0,0.027147,0.303414,386662.5,-0.006009,0.247298,213.980029,0.038829,0.310047,221.591067,0.032403,0.303137,2492.0,0.210884,-0.096774,2481.0,0.220965,-0.106911,2674.0,0.197492,-0.065035,1584.0,0.027904,-0.116564,0.6,-0.1,0.0,7.0,-1.0,-4.0,1.015571,0.006466,0.023341,0.518860,0.057733,0.212228,0.212121,0.036910,-0.026027,0.773478,0.013636,0.039497,"Tampa, FL",45300.0,2022-08-14 14:44:22
123,2022-04-01,1478194.0,65272.0,440000.0,5040.0,28.0,308.0,10606.0,14.0,2.3,791276,11281.0,61.423444,96832749.0,Hillsborough County,FL,2022-04-01,2022-04-30,30,county,5,464,f,"Hillsborough County, FL",None,Florida,FL,All Residential,-1,395000.0,0.045001,0.316667,409000.0,0.057770,0.278125,224.311043,0.048280,0.346934,230.621397,0.040752,0.308417,2275.0,-0.087079,-0.181949,2258.0,-0.089883,-0.165250,2827.0,0.057218,-0.050067,2068.0,0.305556,0.104111,0.9,0.3,0.2,6.0,-1.0,-2.0,1.023400,0.007829,0.024290,0.576703,0.057843,0.194467,0.224371,0.012250,-0.004673,0.765722,-0.007757,0.004169,"Tampa, FL",45300.0,2022-08-14 14:44:22
124,2022-05-01,1478194.0,65272.0,450000.0,5623.0,26.0,510.0,10606.0,14.0,2.3,795747,11281.0,61.423444,96832749.0,Hillsborough County,FL,2022-05-01,2022-05-31,30,county,5,464,f,"Hillsborough County, FL",None,Florida,FL,All Residential,-1,400000.0,0.012658,0.298512,416442.5,0.018197,0.281362,229.088233,0.021297,0.331441,230.514988,-0.000461,0.271711,2392.0,0.051429,-0.091531,2575.0,0.140390,-0.046649,3133.0,0.108242,0.083708,2533.0,0.224855,0.326873,1.1,0.2,0.4,7.0,1.0,1.0,1.019241,-0.004159,0.014135,0.545569,-0.031135,0.112223,0.299645,0.075273,0.064967,0.731262,-0.034460,-0.052151,"Tampa, FL",45300.0,2022-08-14 14:44:22
125,2022-06-01,1478194.0,65272.0,462500.0,6182.0,28.0,629.0,10606.0,14.0,2.8,800604,11281.0,61.423444,96832749.0,Hillsborough County,FL,2022-06-01,2022-06-30,30,county,5,464,f,"Hillsborough County, FL",None,Florida,FL,All Residential,-1,410000.0,0.025000,0.281250,419900.0,0.008302,0.261340,230.164671,0.004699,0.295917,230.516529,0.000007,0.267841,2435.0,0.017977,-0.190223,2315.0,-0.100971,-0.152015,3482.0,0.111395,0.136423,3596.0,0.419660,0.708314,1.5,0.4,0.8,8.0,1.0,2.0,1.010353,-0.008888,0.000411,0.512115,-0.033454,0.019598,0.404616,0.104972,0.125756,0.632397,-0.098865,-0.129141,"Tampa, FL",45300.0,2022-08-14 14:44:22
126,2022-07-01,1478194.0,65272.0,459500.0,6833.0,29.0,645.0,10606.0,14.0,2.7,803151,11281.0,61.423444,96832749.0,Hillsborough County,FL,2022-07-01,2022-07-31,30,county,5,464,f,"Hillsborough County, FL",None,Florida,FL,All Residential,-1,407582.5,-0.005896,0.254100,415000.0,-0.011669,0.213805,230.427925,0.001144,0.266297,231.650673,0.004920,0.250914,2098.0,-0.138398,-0.224112,2240.0,-0.032397,-0.169139,2991.0,-0.141011,-0.053181,4208.0,0.170189,0.720360,2.0,0.5,1.1,10.0,2.0,3.0,0.999577,-0.010776,-0.009105,0.404194,-0.107921,-0.075465,0.521150,0.116534,0.229654,0.488839,-0.143558,-0.237422,"Tampa, FL",45300.0,2022-08-14 14:44:22

#### <font color="purple">5. Zipcode Region</font> üèò

##### <font color="orange">Standard Query</font> ‚ú®

In [ ]:
zipcode = "33610" # enter state code abbreviations
url = "https://us-housing-market-data.p.rapidapi.com/getZipcode"

querystring = {"zipcode":zipcode}

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)
df_zipcode = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_zipcode)))
print('Num of columns: {}'.format(len(df_zipcode.columns)))
print('Last updated: {}'.format(df_zipcode['last_updated'].unique().tolist()[0]))
print('Lastest period: {}'.format(df_zipcode['period_end'].max()))
df_zipcode.head()

Num of rows: 462
Num of columns: 59
Last updated: 2022-08-14 14:44:22
Lastest period: 2022-07-31

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated,zipcode
0,2018-06-01,2018-08-31,90,zip code,2,14276,f,Zip Code: 33610,None,Florida,FL,All Residential,-1,149428.5,-0.026207,0.149450,149450.0,0.010309,0.086909,113.358204,0.017391,0.283887,113.494829,0.079076,0.160753,132.0,0.015385,-0.102041,45.0,0.216216,0.125,187.0,0.246667,0.230263,122.0,0.270833,0.140187,None,None,None,26.0,-1.5,1.0,0.969534,-0.002257,0.009052,0.19697,0.012354,0.013296,None,None,None,0.577778,0.010210,0.177778,"Tampa, FL",45300,2022-08-14 14:44:22,33610
1,2012-05-01,2012-07-31,90,zip code,2,14276,f,Zip Code: 33610,None,Florida,FL,Townhouse,13,98000.0,0.000000,0.171898,109000.0,0.045313,0.191908,54.884742,0.010101,0.148717,60.332404,0.019279,0.135868,25.0,-0.107143,1.500000,NaN,NaN,NaN,52.0,0.529412,1.166667,67.0,0.313725,0.367347,None,None,None,183.0,12.0,88.0,0.955787,0.010509,0.015904,0.20000,0.092857,0.200000,None,None,None,NaN,NaN,NaN,"Tampa, FL",45300,2022-08-14 14:44:22,33610
2,2020-09-01,2020-11-30,90,zip code,2,14276,f,Zip Code: 33610,None,Florida,FL,Single Family Residential,6,205000.0,0.000000,0.281250,215000.0,0.003669,0.265450,148.677686,-0.016294,0.183206,157.704240,0.022946,0.146940,125.0,-0.119718,0.086957,32.0,-0.179487,-0.200,131.0,0.082645,-0.176101,81.0,0.080000,-0.325000,None,None,None,18.0,-18.0,-1.0,0.984465,0.005700,0.008112,0.28800,-0.000732,0.035826,None,None,None,0.468750,-0.044071,-0.056250,"Tampa, FL",45300,2022-08-14 14:44:22,33610
3,2017-08-01,2017-10-31,90,zip code,2,14276,f,Zip Code: 33610,None,Florida,FL,Townhouse,13,138950.0,-0.007500,-0.007500,144900.0,0.003463,0.097727,85.123276,0.050052,0.005265,84.630728,0.012469,0.057172,24.0,-0.111111,0.846154,3.0,0.000000,-0.500,21.0,0.050000,0.235294,11.0,0.571429,0.222222,None,None,None,12.0,3.0,-25.0,0.981628,0.012549,-0.003822,0.12500,-0.023148,-0.182692,None,None,None,0.333333,-0.333333,-0.500000,"Tampa, FL",45300,2022-08-14 14:44:22,33610
4,2014-04-01,2014-06-30,90,zip code,2,14276,f,Zip Code: 33610,None,Florida,FL,Multi-Family (2-4 Unit),4,90000.0,0.000000,NaN,24700.0,-0.173913,NaN,46.524742,-0.017811,NaN,11.160253,-0.040368,NaN,4.0,0.333333,NaN,NaN,NaN,NaN,2.0,1.000000,NaN,3.0,0.000000,NaN,None,None,None,352.0,0.0,NaN,0.932546,-0.039676,NaN,0.00000,0.000000,NaN,None,None,None,NaN,NaN,NaN,"Tampa, FL",45300,2022-08-14 14:44:22,33610

##### <font color="orange">Enriched Query</font> üåü

In [ ]:
url = "https://us-housing-market-data.p.rapidapi.com/getZipcodeEnriched"

querystring = {"zipcode":zipcode}

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)
df_zipcode_e = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_zipcode_e)))
print('Num of columns: {}'.format(len(df_zipcode_e.columns)))
df_zipcode_e.tail()

Num of rows: 72
Num of columns: 71

,census.year,census.state,census.zipcode,census.median_household_income,census.median_rent_all_bds,census.median_rent_0_beds,census.median_rent_1_beds,census.median_rent_2_beds,census.median_rent_3_beds,census.median_rent_4_beds,census.median_rent_5+_beds,redfin.period_begin,redfin.period_end,redfin.period_duration,redfin.region_type,redfin.region_type_id,redfin.table_id,redfin.is_seasonally_adjusted,redfin.region,redfin.city,redfin.state,redfin.state_code,redfin.property_type,redfin.property_type_id,redfin.median_sale_price,redfin.median_sale_price_mom,redfin.median_sale_price_yoy,redfin.median_list_price,redfin.median_list_price_mom,redfin.median_list_price_yoy,redfin.median_ppsf,redfin.median_ppsf_mom,redfin.median_ppsf_yoy,redfin.median_list_ppsf,redfin.median_list_ppsf_mom,redfin.median_list_ppsf_yoy,redfin.homes_sold,redfin.homes_sold_mom,redfin.homes_sold_yoy,redfin.pending_sales,redfin.pending_sales_mom,redfin.pending_sales_yoy,redfin.new_listings,redfin.new_listings_mom,redfin.new_listings_yoy,redfin.inventory,redfin.inventory_mom,redfin.inventory_yoy,redfin.months_of_supply,redfin.months_of_supply_mom,redfin.months_of_supply_yoy,redfin.median_dom,redfin.median_dom_mom,redfin.median_dom_yoy,redfin.avg_sale_to_list,redfin.avg_sale_to_list_mom,redfin.avg_sale_to_list_yoy,redfin.sold_above_list,redfin.sold_above_list_mom,redfin.sold_above_list_yoy,redfin.price_drops,redfin.price_drops_mom,redfin.price_drops_yoy,redfin.off_market_in_two_weeks,redfin.off_market_in_two_weeks_mom,redfin.off_market_in_two_weeks_yoy,redfin.parent_metro_region,redfin.parent_metro_region_metro_code,redfin.last_updated,redfin.zipcode,redfin.year
67,2020,12,33610,59708.5,1048.0,901.5,820.5,990.0,1178.0,1433.0,None,2020-06-01,2020-08-31,90,zip code,2,14276,f,Zip Code: 33610,None,Florida,FL,Single Family Residential,6,200000.0,0.025641,0.286174,214984.0,0.023977,0.243041,144.545992,0.039278,0.183283,151.225059,0.011336,0.194646,141.0,0.137097,0.014388,43.0,-0.156863,-0.044444,144.0,-0.152941,-0.127273,81.0,-0.205882,-0.256881,None,None,None,52.0,-4.5,27.0,0.974224,-0.003532,0.004063,0.283688,-0.022764,0.039084,None,None,None,0.395349,-0.134063,-0.249096,"Tampa, FL",45300,2022-08-14 14:44:22,33610,2020
68,2020,12,33610,59708.5,1048.0,901.5,820.5,990.0,1178.0,1433.0,None,2020-03-01,2020-05-31,90,zip code,2,14276,f,Zip Code: 33610,None,Florida,FL,Single Family Residential,6,188995.0,0.049972,0.181219,188450.0,0.077473,0.177816,137.049180,0.000000,0.117761,143.048510,0.049897,0.120579,117.0,-0.048780,-0.158273,44.0,0.375000,0.189189,146.0,0.149606,-0.087500,115.0,0.026786,0.017699,None,None,None,57.0,6.0,22.0,0.975526,0.010822,0.009069,0.290598,0.071086,0.002829,None,None,None,0.454545,0.235795,0.022113,"Tampa, FL",45300,2022-08-14 14:44:22,33610,2020
69,2020,12,33610,59708.5,1048.0,901.5,820.5,990.0,1178.0,1433.0,None,2020-12-01,2021-02-28,90,zip code,2,14276,f,Zip Code: 33610,None,Florida,FL,Single Family Residential,6,189500.0,-0.052500,0.115362,213000.0,0.000000,0.217839,156.503378,0.026662,0.210146,169.878654,0.035351,0.233165,116.0,-0.008547,-0.025210,47.0,0.146341,0.342857,141.0,0.044444,-0.040816,65.0,-0.029851,-0.488189,None,None,None,23.0,-3.0,-18.0,0.982061,-0.001772,0.031667,0.267241,-0.006263,0.115981,None,None,None,0.680851,0.266217,0.195137,"Tampa, FL",45300,2022-08-14 14:44:22,33610,2020
70,2020,12,33610,59708.5,1048.0,901.5,820.5,990.0,1178.0,1433.0,None,2020-02-01,2020-04-30,90,zip code,2,14276,f,Zip Code: 33610,None,Florida,FL,Single Family Residential,6,180000.0,0.063830,0.125704,174900.0,-0.022905,0.093809,137.049180,0.058667,0.151098,136.250000,-0.010949,0.068004,123.0,0.008197,-0.061069,32.0,0.066667,-0.238095,127.0,-0.248521,-0.175325,112.0,-0.157895,0.087379,None,None,None,51.0,4.0,13.0,0.964704,0.012181,-0.002921,0.219512,0.055578,-0.001862,None,None,None,0.218750,-0.247917,-0.233631,"Tampa, FL",45300,2022-08-14 14:44:22,33610,2020
71,2020,12,33610,59708.5,1048.0,901.5,820.5,990.0,1178.0,1433.0,None,2020-01-01,2020-03-31,90,zip code,2,14276,f,Zip Code: 33610,None,Florida,FL,Single Family Residential,6,169200.0,-0.004120,0.158904,179000.0,0.023442,0.119450,129.454427,0.000993,0.035635,137.758297,0.000000,0.118253,122.0,0.025210,0.008264,30.0,-0.142857,-0.268293,169.0,0.149660,0.090323,133.0,0.047244,0.209091,None,None,None,47.0,6.0,11.5,0.952523,0.002129,-0.008045,0.163934,0.012674,-0.009619,None,None,None,0.466667,-0.019048,-0.143089,"Tampa, FL",45300,2022-08-14 14:44:22,33610,2020

#### <font color="purple">6. Neighborhood Region</font> üèò

##### <font color="orange">Search Valid Neighborhood Ids</font> üîç

In [ ]:
url = "https://us-housing-market-data.p.rapidapi.com/getRegionId"

querystring = {"region_type":"neighborhood"}

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)
df_neighborhood_ids = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_neighborhood_ids)))
df_neighborhood_ids.head()

Num of rows: 38459

      region_id                                        region          type
43555    119928  Anaheim, CA - The Highlands at Anaheim Hills  neighborhood
43556    352009                      Memphis, TN - River Oaks  neighborhood
43557    764968     Wilmington, NC - Millbrook-Masonboro Loop  neighborhood
43558    760210                          Mobile, AL - Melrose  neighborhood
43559    549879                   Warren, RI - Downton Warren  neighborhood

In [ ]:
neighborhood_id_search_str = 'Ybor'
df_neighborhood_id_filter = df_neighborhood_ids.loc[
    df_neighborhood_ids['region'].str.contains(neighborhood_id_search_str)]
df_neighborhood_id_filter

      region_id                                   region          type
48318     76738           Tampa, FL - Historic Ybor City  neighborhood
49307    557460  Tampa, FL - Ybor City Historic District  neighborhood
51448     70147           Tampa, FL - East Ybor Historic  neighborhood
54845    557451                   Tampa, FL - North Ybor  neighborhood
58616    134740                   Tampa, FL - V. M. Ybor  neighborhood
67621    764519                 Tampa, FL - Ybor Heights  neighborhood

##### <font color="orange">Standard Query</font> ‚ú®

In [ ]:
neighborhood_id = "76738" # enter neighborhood id here
url = "https://us-housing-market-data.p.rapidapi.com/getNeighborhood"

querystring = {"neighborhood_id":neighborhood_id}

headers = {
	"X-RapidAPI-Key": rapid_api_key,
	"X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)
df_neighborhood = pd.DataFrame.from_dict(response.json(), orient='index')
print('Num of rows: {}'.format(len(df_neighborhood)))
print('Num of columns: {}'.format(len(df_neighborhood.columns)))
print('Last updated: {}'.format(df_neighborhood['last_updated'].unique().tolist()[0]))
print('Lastest period: {}'.format(df_neighborhood['period_end'].max()))
df_neighborhood.head()

Num of rows: 419
Num of columns: 58
Last updated: 2022-08-14 14:44:22
Lastest period: 2022-07-31

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2019-12-01,2020-02-29,90,neighborhood,1,76738,f,"Tampa, FL - Historic Ybor City",Tampa,Florida,FL,All Residential,-1,133500.0,-0.200599,-0.157729,170000.0,-0.291371,0.203540,186.011905,-0.024707,0.068029,188.988095,-0.084850,-0.060998,17.0,-0.227273,0.416667,7.0,1.333333,1.333333,13.0,-0.133333,-0.071429,14.0,-0.300000,-0.222222,None,None,None,94.0,18.5,33.5,0.971862,-0.000642,0.004418,0.058824,-0.032086,0.058824,None,None,None,0.285714,-0.380952,-0.047619,"Tampa, FL",45300,2022-08-14 14:44:22
1,2012-01-01,2012-03-31,90,neighborhood,1,76738,f,"Tampa, FL - Historic Ybor City",Tampa,Florida,FL,Townhouse,13,135000.0,0.125000,NaN,140000.0,0.000000,NaN,79.646018,-0.138496,NaN,82.233608,0.000000,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,2.0,0.000000,NaN,2.0,-0.333333,NaN,None,None,None,70.0,-33.0,NaN,0.964286,-0.136632,NaN,0.000000,-1.000000,NaN,None,None,None,0.000000,NaN,NaN,"Tampa, FL",45300,2022-08-14 14:44:22
2,2018-04-01,2018-06-30,90,neighborhood,1,76738,f,"Tampa, FL - Historic Ybor City",Tampa,Florida,FL,Townhouse,13,232000.0,0.000000,0.007819,259500.0,0.000000,0.140910,209.009009,0.000000,0.296055,209.274194,0.000000,0.314975,1.0,0.000000,-0.500000,NaN,NaN,NaN,3.0,0.000000,0.500000,2.0,0.000000,NaN,None,None,None,NaN,NaN,NaN,1.000000,0.000000,-0.011004,0.000000,0.000000,-0.500000,None,None,None,NaN,NaN,NaN,"Tampa, FL",45300,2022-08-14 14:44:22
3,2017-01-01,2017-03-31,90,neighborhood,1,76738,f,"Tampa, FL - Historic Ybor City",Tampa,Florida,FL,All Residential,-1,199000.0,0.421429,0.009384,144450.0,0.032523,0.179665,165.477533,0.147311,0.102931,162.567976,0.028396,0.187011,12.0,0.333333,0.000000,1.0,-0.857143,-0.800000,16.0,-0.058824,0.142857,7.0,0.000000,-0.461538,None,None,None,19.0,0.0,-81.0,0.967014,0.002683,-0.006535,0.083333,0.083333,0.000000,None,None,None,0.000000,-0.714286,-0.600000,"Tampa, FL",45300,2022-08-14 14:44:22
4,2013-11-01,2014-01-31,90,neighborhood,1,76738,f,"Tampa, FL - Historic Ybor City",Tampa,Florida,FL,All Residential,-1,94500.0,-0.091346,0.400000,84950.0,-0.052954,0.089103,98.039216,-0.017622,0.122735,104.166667,0.008517,0.205774,17.0,-0.055556,1.125000,4.0,0.000000,1.000000,18.0,-0.100000,-0.142857,20.0,0.052632,-0.047619,None,None,None,58.0,-6.0,-59.0,0.966989,-0.000887,-0.005491,0.235294,0.068627,-0.139706,None,None,None,0.000000,0.000000,0.000000,"Tampa, FL",45300,2022-08-14 14:44:22

### <font color="green">Section #2 - Loops</font> üèô
Get data for multiple regions

In [ ]:
# get all neighborhoods in a single city
city = 'Tampa, FL'
df_neighborhood_fltr = df_neighborhood_ids.loc[
    df_neighborhood_ids['region'].str.contains(city)]
neighborhood_ids_list = df_neighborhood_fltr['region_id'].tolist()
print('Num of neighborhoods:', len(neighborhood_ids_list))
print('Sample neighborhoods:', df_neighborhood_fltr['region'].tolist()[:5])

Num of neighborhoods: 120
Sample neighborhoods: ['Tampa, FL - Courier City-Oscawana', 'Tampa, FL - Sun Bay South', 'Tampa, FL - Baybridge', 'Tampa, FL - Belmar Gardens', 'Tampa, FL - Academy of the Holy Names']

In [ ]:
subset_neighborhoods_list = ['Tampa, FL - Lowry Park North',
 'Tampa, FL - Lowry Park Central',
 'Tampa, FL - Historic Ybor City',
 'Tampa, FL - East Ybor Historic',
 'Tampa, FL - V. M. Ybor',
 'Tampa, FL - North Ybor',
 'Tampa, FL - Ybor Heights',
 'Tampa, FL - Ybor City Historic District',
 'Tampa, FL - Old Seminole Heights'
 'Tampa, FL - South Seminole Heights', 
 'Tampa, FL - Southeast Seminole Heights',
 'Tampa, FL - East Seminole Heights',
 'Tampa, FL - Seminole Heights Historic District',
 'Tampa, FL - Seminole Heights',
 'Tampa, FL - Riverside Heights',
 'Tampa, FL - West Riverside Heights',
 'Tampa, FL - Eastern Heights',
 'Tampa, FL - Tampa Heights',
 'Tampa, FL - Tampa Heights Historic District'
 'Tampa, FL - Hyde Park Historic District',
 'Tampa, FL - Hyde Park North',
 'Tampa, FL - Hyde Park',
 'Tampa, FL - North Hyde Park',
 'Tampa, FL - Historic Hyde Park North']
subset_ids_list = df_neighborhood_fltr\
  .loc[df_neighborhood_fltr['region'].isin(subset_neighborhoods_list)]\
  ['region_id'].tolist()
print('Num of neighborhoods in subset: {}'.format(str(len(subset_ids_list))))

Num of neighborhoods in subset: 20

In [ ]:
# get neighborhood data
df_list = [] # empty list

# iterate through each neighborhood id in the list
for n_id in subset_ids_list:
  url = "https://us-housing-market-data.p.rapidapi.com/getNeighborhood"

  querystring = {"neighborhood_id": n_id}

  headers = {
    "X-RapidAPI-Key": rapid_api_key,
    "X-RapidAPI-Host": "us-housing-market-data.p.rapidapi.com"
  }

  # make request
  response = requests.request("GET", url, headers=headers, params=querystring)
  
  # convert to dataframe
  _df = pd.DataFrame.from_dict(response.json(), orient='index') 
  df_list.append(_df) # append dataframe to list
  time.sleep(0.2) # pause (Pro tier = 5 requests per second)

In [ ]:
df_merge = pd.concat(df_list)
print('Num of rows: {}'.format(len(df_merge)))
print('Num of columns: {}'.format(len(df_merge.columns)))
df_merge.head()

Num of rows: 6949
Num of columns: 58

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2019-12-01,2020-02-29,90,neighborhood,1,76738,f,"Tampa, FL - Historic Ybor City",Tampa,Florida,FL,All Residential,-1,133500.0,-0.200599,-0.157729,170000.0,-0.291371,0.203540,186.011905,-0.024707,0.068029,188.988095,-0.084850,-0.060998,17.0,-0.227273,0.416667,7.0,1.333333,1.333333,13.0,-0.133333,-0.071429,14.0,-0.300000,-0.222222,None,None,None,94.0,18.5,33.5,0.971862,-0.000642,0.004418,0.058824,-0.032086,0.058824,None,None,None,0.285714,-0.380952,-0.047619,"Tampa, FL",45300,2022-08-14 14:44:22
1,2012-01-01,2012-03-31,90,neighborhood,1,76738,f,"Tampa, FL - Historic Ybor City",Tampa,Florida,FL,Townhouse,13,135000.0,0.125000,NaN,140000.0,0.000000,NaN,79.646018,-0.138496,NaN,82.233608,0.000000,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,2.0,0.000000,NaN,2.0,-0.333333,NaN,None,None,None,70.0,-33.0,NaN,0.964286,-0.136632,NaN,0.000000,-1.000000,NaN,None,None,None,0.000000,NaN,NaN,"Tampa, FL",45300,2022-08-14 14:44:22
2,2018-04-01,2018-06-30,90,neighborhood,1,76738,f,"Tampa, FL - Historic Ybor City",Tampa,Florida,FL,Townhouse,13,232000.0,0.000000,0.007819,259500.0,0.000000,0.140910,209.009009,0.000000,0.296055,209.274194,0.000000,0.314975,1.0,0.000000,-0.500000,NaN,NaN,NaN,3.0,0.000000,0.500000,2.0,0.000000,NaN,None,None,None,NaN,NaN,NaN,1.000000,0.000000,-0.011004,0.000000,0.000000,-0.500000,None,None,None,NaN,NaN,NaN,"Tampa, FL",45300,2022-08-14 14:44:22
3,2017-01-01,2017-03-31,90,neighborhood,1,76738,f,"Tampa, FL - Historic Ybor City",Tampa,Florida,FL,All Residential,-1,199000.0,0.421429,0.009384,144450.0,0.032523,0.179665,165.477533,0.147311,0.102931,162.567976,0.028396,0.187011,12.0,0.333333,0.000000,1.0,-0.857143,-0.800000,16.0,-0.058824,0.142857,7.0,0.000000,-0.461538,None,None,None,19.0,0.0,-81.0,0.967014,0.002683,-0.006535,0.083333,0.083333,0.000000,None,None,None,0.000000,-0.714286,-0.600000,"Tampa, FL",45300,2022-08-14 14:44:22
4,2013-11-01,2014-01-31,90,neighborhood,1,76738,f,"Tampa, FL - Historic Ybor City",Tampa,Florida,FL,All Residential,-1,94500.0,-0.091346,0.400000,84950.0,-0.052954,0.089103,98.039216,-0.017622,0.122735,104.166667,0.008517,0.205774,17.0,-0.055556,1.125000,4.0,0.000000,1.000000,18.0,-0.100000,-0.142857,20.0,0.052632,-0.047619,None,None,None,58.0,-6.0,-59.0,0.966989,-0.000887,-0.005491,0.235294,0.068627,-0.139706,None,None,None,0.000000,0.000000,0.000000,"Tampa, FL",45300,2022-08-14 14:44:22

### <font color="green">Section #3 - Visualization</font> üìà
Visualize housing and economic data trends over time

In [ ]:
max_period = df_merge['period_begin'].max()
print('Max period: {}'.format(max_period))

Max period: 2022-05-01

In [ ]:
# filter property type = single family
df_sf = df_merge.loc[
    (df_merge['property_type'] == 'Single Family Residential')]\
    .sort_values(by="period_begin")

##### <font color="orange">‚ùì Which neighborhoods are most expensive ‚ùì</font>

In [ ]:
df_sf.loc[(df_sf['period_begin'] == max_period)]\
  .sort_values(by=['median_sale_price'], ascending=False)\
  [['region', 'median_sale_price']].head()

                                   region  median_sale_price
15                  Tampa, FL - Hyde Park          1215000.0
464  Tampa, FL - Historic Hyde Park North          1100000.0
403           Tampa, FL - Hyde Park North           890000.0
293         Tampa, FL - Riverside Heights           650000.0
34            Tampa, FL - North Hyde Park           603500.0

In [ ]:
df_plot = df_sf.loc[(df_sf['period_begin'] == max_period)]
fig = px.box(df_plot, y="median_sale_price", title="Median Sale Price")
fig.show()

##### <font color="orange">‚ùì Which neighborhoods appreciated the most ‚ùì</font>

In [ ]:
df_sf.loc[(df_sf['period_begin'] == max_period)]\
  .sort_values(by=['median_sale_price_yoy'], ascending=False)\
  [['region', 'median_sale_price_yoy']].head()

                                region  median_sale_price_yoy
211  Tampa, FL - East Seminole Heights               0.586364
285             Tampa, FL - V. M. Ybor               0.581395
136          Tampa, FL - Tampa Heights               0.503401
34         Tampa, FL - North Hyde Park               0.499379
219     Tampa, FL - East Ybor Historic               0.494975

In [ ]:
df_plot = df_sf.loc[(df_sf['period_begin'] == max_period)]\
  .sort_values(by=['median_sale_price_yoy'], ascending=False)
fig = px.bar(df_plot, x='region', y='median_sale_price_yoy', title='Median Sale Price YoY')
fig.show()

##### <font color="orange">‚ùì Historical ‚ùì</font>

In [ ]:
fig = px.line(df_sf, x="period_begin", y="median_sale_price", 
              color="region", title='Median Sale Price')
fig.show()

In [ ]:
fig = px.line(df_sf, x="period_begin", y="median_ppsf", 
              color="region", title='Median PPSF')
fig.show()

In [ ]:
fig = px.line(df_sf, x="period_begin", y="inventory", 
              color="region", title='Inventory')
fig.show()

# End Notebook